### PR TITLE
update barman class to allow barman::server definition via hiera

### PR DESCRIPTION
**Pull request by damnski**
Allow hiera data to be passed in for barman::server define.

### CODE REVIEW

**Comment by fcanovai** [comment]
Hi,

I've looked at the patch and I don't get the reason of the difference between the deep_merge and the simple hiera_hash lookup (deprecated by Puppet). Moreover, the `servers` value should already receive its value from hiera, why a new lookup?

**Comment by damnski** [comment]
The deep_merge lookup is to support merging class hash data, if present, and hiera hash data.  The hiera_hash lookup is to support puppet versions less than 4 which do not merge hashes by default, but perform a priority lookup.
 I removed the deep_merge - it's more of a localized-to-us edge case - but left the hiera_hash.  I also tweaked the README for clarity.

here's version 3.8.7 where it sets priority lookup (last parameter is nil, causing priority lookup):
https://github.com/puppetlabs/puppet/blob/3.8.7/lib/puppet/indirector/hiera.rb#L19

and here's version 4.0.0 where they changed that behavior:
https://github.com/puppetlabs/puppet/blob/4.0.0/lib/puppet/indirector/hiera.rb#L21

**Comment by damnski** [comment]
I just pushed again after discussing the pros and cons of the approach with my colleague https://github.com/rabbitt.   Synopsis: use deep_merge with barman::servers hash to merge any class data, initial priority lookup data, and, or multiple levels of hiera data.  This will support version 3 and up.

**Comment by xstasi** [comment]
Merged, thank you!

**Pull request merged**
