### PR TITLE
make exported_ipaddress *actually* configurable

### PR DESCRIPTION
**Pull request by igalic**
pull default into class declaration to allow more configurability.

### CODE REVIEW

**Comment by mnencia** [comment]
I don't like to allow it. If you want to configure a wider access, you can always manually use a pg_hba_rule resource. The purpose of that function is to permit the access to the barman server only.

**Comment by igalic** [comment]
yes. but that access assumes ipv4 only, and i have an ipv6 only network.

**Comment by mnencia** [comment]
Ok, I got it. You are right.

**Comment by igalic** [comment]
thanks @mnencia!

**Pull request merged**
