### PR TITLE
add support for more barman config options

### PR DESCRIPTION
**Pull request by costela**
These patches add support for most of the barman config file options, both in the server as well as the global context, in particular streaming_archiver.
Additionally, support for accessing PostgreSQL on a different port than default is also supported.

### CODE REVIEW

**Comment by costela** [comment]
Hm, not entirely sure why the build is failing. Will have to check it next week (if nobody here has any ideas in the meantime).

**Comment by costela** [comment]
Hm... not entirely sure why the build is failing. The first two errors are obviously spurious (`json\_pure` downloaded just fine for job 2) and the `puppetversion` issues in the other jobs seem unrelated at first glance. I'm trying to reproduce it locally to be sure.

**Comment by Behner** [comment]
Thanks for your hard work! Can't wait to try out Barman 2.0, once this is merged.

**Comment by costela** [comment]
Build now works.
The workaround in ff577fd could have side-effects I haven't considered. It feels a bit dirty and I haven't seen it being used in other projects, but this doesn't mean much... Any thoughts?

**Pull request merged**
